
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FCHAVE = 4;
  public static final int VERDADEIRO = 29;
  public static final int ADICAO = 24;
  public static final int MENORQ = 23;
  public static final int IMPRIMIR = 20;
  public static final int MULTIPLICACAO = 26;
  public static final int VIRGULA = 15;
  public static final int PONTO = 27;
  public static final int E = 22;
  public static final int STATIC = 6;
  public static final int NOT = 33;
  public static final int IGUAL = 21;
  public static final int CLASS = 2;
  public static final int ACHAVE = 3;
  public static final int MAIN = 8;
  public static final int IF = 17;
  public static final int THIS = 31;
  public static final int ACOLCHETE = 10;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int PVIRGULA = 14;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int NUMBER = 35;
  public static final int FCOLCHETE = 11;
  public static final int VOID = 7;
  public static final int ELSE = 18;
  public static final int WHILE = 19;
  public static final int PUBLIC = 5;
  public static final int FALSO = 30;
  public static final int EXTENDS = 13;
  public static final int APARENTESE = 9;
  public static final int FPARENTESE = 12;
  public static final int BOOLEANO = 36;
  public static final int STRING = 34;
  public static final int SUBTRACAO = 25;
  public static final int TAMANHO = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ACHAVE",
  "FCHAVE",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "APARENTESE",
  "ACOLCHETE",
  "FCOLCHETE",
  "FPARENTESE",
  "EXTENDS",
  "PVIRGULA",
  "VIRGULA",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "IMPRIMIR",
  "IGUAL",
  "E",
  "MENORQ",
  "ADICAO",
  "SUBTRACAO",
  "MULTIPLICACAO",
  "PONTO",
  "TAMANHO",
  "VERDADEIRO",
  "FALSO",
  "THIS",
  "NEW",
  "NOT",
  "STRING",
  "NUMBER",
  "BOOLEANO"
  };
}

